name: CI
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: fetch ppa for cmake
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq cmake g++-9 docker
    - name: build concepts
      env:
        CMAKE_PATH: /usr/bin/cmake
      run: |
        docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp g++:latest g++ -std=c++2a -fconcepts main.cpp -o concept
